### PR TITLE
Add Java 11 support

### PR DESCRIPTION
**Pull request by senthalan**
## Purpose
Add Java 11 support

### CODE REVIEW

**Comment by omindu** [comment]
@Seralahthan what is the impact of this change ?

**Comment by madurangasiriwardena** [comment]
@omindu I think you should ask the above question from @senthalan.

**Comment by omindu** [comment]
> @omindu I think you should ask the above question from @senthalan.
😂. Yeah should be @senthalan

**Comment by senthalan** [comment]
@omindu, this will skip annotation scanning during the server start up

**Pull request merged**
